# Generated by Django 5.2.5 on 2025-08-14 15:16

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdvertisementImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(help_text='Image file stored in Cloudinary.', max_length=255, verbose_name='image')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the category.', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Favorite',
                'verbose_name_plural': 'Favorites',
            },
        ),
        migrations.CreateModel(
            name='RentAdvertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the advertisement.', max_length=255)),
                ('description', models.TextField(help_text='Detailed description of the property.')),
                ('price', models.DecimalField(decimal_places=2, help_text='Price of the property.', max_digits=12)),
                ('approved', models.BooleanField(default=False, help_text='Whether the advertisement is approved by admin.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the advertisement was created.')),
            ],
        ),
        migrations.CreateModel(
            name='RentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('closed', 'Closed')], default='pending', help_text='Status of the rent request.', max_length=10)),
                ('message', models.TextField(blank=True, default='', help_text='Optional message from the sender.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the request was created.')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(help_text='Rating given by the user (1-5).')),
                ('comment', models.TextField(blank=True, help_text='Optional comment provided by the user.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the review was created.')),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
            },
        ),
    ]
