# Generated by Django 5.2.5 on 2025-08-14 15:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rent', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='user',
            field=models.ForeignKey(help_text='User who favorited the advertisement.', on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rentadvertisement',
            name='category',
            field=models.ForeignKey(help_text='Category of the property.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='rent.category'),
        ),
        migrations.AddField(
            model_name='rentadvertisement',
            name='owner',
            field=models.ForeignKey(help_text='User who created the advertisement.', on_delete=django.db.models.deletion.CASCADE, related_name='ads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='favorite',
            name='advertisement',
            field=models.ForeignKey(help_text='Advertisement marked as favorite.', on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='rent.rentadvertisement'),
        ),
        migrations.AddField(
            model_name='advertisementimage',
            name='advertisement',
            field=models.ForeignKey(help_text='Advertisement this image belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='rent.rentadvertisement'),
        ),
        migrations.AddField(
            model_name='rentrequest',
            name='advertisement',
            field=models.ForeignKey(help_text='Advertisement for which the request is made.', on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='rent.rentadvertisement'),
        ),
        migrations.AddField(
            model_name='rentrequest',
            name='sender',
            field=models.ForeignKey(help_text='User who sent the rent request.', on_delete=django.db.models.deletion.CASCADE, related_name='rent_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='review',
            name='advertisement',
            field=models.ForeignKey(help_text='Advertisement being reviewed.', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='rent.rentadvertisement'),
        ),
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(help_text='User who wrote the review.', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('user', 'advertisement')},
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('advertisement', 'user')},
        ),
    ]
