# Generated by Django 5.2.5 on 2025-09-12 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2025-09-12 14:30:00', help_text='Timestamp when the advertisement was created.'),
            preserve_default=False,
        ),
    ]
