# Generated by Django 5.2.5 on 2025-09-13 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0003_category_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentadvertisement',
            name='booked',
            field=models.BooleanField(default=False, help_text='Whether the advertisement is booked.'),
        ),
        migrations.AlterField(
            model_name='rentrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('canceled', 'Canceled'), ('completed', 'Completed'), ('advanced', 'Advanced'), ('closed', 'Closed')], default='pending', help_text='Status of the rent request.', max_length=10),
        ),
    ]
