# Generated by Django 5.2.5 on 2025-09-22 14:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0004_rentadvertisement_booked_alter_rentrequest_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='rentadvertisement',
            name='accepted',
            field=models.BooleanField(default=False, help_text='Whether the advertisement is booked.'),
        ),
        migrations.AddField(
            model_name='rentadvertisement',
            name='accepted_for',
            field=models.ForeignKey(blank=True, help_text='User who successfully accepted this advertisement via request.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_ads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rentadvertisement',
            name='booked_by',
            field=models.ForeignKey(blank=True, help_text='User who successfully booked this advertisement via payment.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booked_ads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='BDT', max_length=10)),
                ('payment_type', models.CharField(choices=[('rent', 'Rent'), ('security_deposit', 'Security Deposit'), ('other', 'Other')], default='rent', max_length=30)),
                ('transaction_id', models.CharField(max_length=200, unique=True)),
                ('gateway_response', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='initiated', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rent_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='rent.rentrequest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
