# Generated by Django 5.2.5 on 2025-09-27 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0005_rentadvertisement_accepted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentrequest',
            name='additional_address',
            field=models.TextField(blank=True, default='', help_text='Optional additional address details.'),
        ),
    ]
