# Generated by Django 5.2.5 on 2025-09-27 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0006_rentrequest_additional_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentrequest',
            name='additional_name',
            field=models.CharField(blank=True, default='', help_text='Optional additional name for the rental.', max_length=255),
        ),
        migrations.AddField(
            model_name='rentrequest',
            name='additional_phone',
            field=models.CharField(blank=True, default='', help_text='Optional additional phone number for the rental.', max_length=20),
        ),
    ]
