# Generated by Django 5.2.5 on 2025-10-18 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0007_rentrequest_additional_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', help_text='Status of the category.', max_length=10),
        ),
    ]
